/**
 * Cookie refresh for yt-dlp: when cookies are stale (by real expiry), fetch and write.
 * Used by the worker so cookie refresh runs without the Express backend.
 */

import fs from 'node:fs';
import path from 'node:path';
import { getYtDlpCookieExpiry } from './cookieExpiry.js';
import { config } from '../config.js';

const REFRESH_BEFORE_DAYS = 2;
const DEFAULT_COOKIE_SOURCE =
  'https://raw.githubusercontent.com/ytdl-org/youtube-dl/master/youtube-dl/cookie-file.txt';
const FETCH_TIMEOUT_MS = 10_000;

function minimalNetscapeCookies(): string {
  return `# Netscape HTTP Cookie File
# Generated by BatchTube cookie refresh (placeholder - replace with browser export for age-restricted)

`;
}

/**
 * True if cookie file is missing, expired, or expiring within REFRESH_BEFORE_DAYS.
 */
export function isCookieStale(cookiePath: string): boolean {
  const p = cookiePath?.trim();
  if (!p) return false;
  if (!fs.existsSync(path.normalize(p))) return true;
  const info = getYtDlpCookieExpiry(p);
  if (!info) return true;
  if (info.isExpired) return true;
  if (info.expiresInDays <= REFRESH_BEFORE_DAYS) return true;
  return false;
}

/**
 * Fetch cookie content from URL or generate minimal. Write to cookiePath.
 */
export async function refreshCookies(cookiePath: string): Promise<boolean> {
  const p = path.normalize(cookiePath.trim());
  const dir = path.dirname(p);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch (e) {
    console.error('[cookieRefresh] Failed to create cookie dir:', dir, e);
    return false;
  }

  const source = process.env.COOKIE_REFRESH_URL?.trim() || DEFAULT_COOKIE_SOURCE;
  let content: string;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    const res = await fetch(source, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; BatchTube/1.0)' },
      signal: controller.signal
    });
    clearTimeout(timeoutId);
    if (res.ok) {
      const text = await res.text();
      if (text && text.length > 100) content = text;
      else content = minimalNetscapeCookies();
    } else {
      content = minimalNetscapeCookies();
    }
  } catch (e) {
    console.warn('[cookieRefresh] Fetch failed, writing minimal:', (e as Error).message);
    content = minimalNetscapeCookies();
  }

  try {
    fs.writeFileSync(p, content, 'utf8');
    console.log(
      JSON.stringify({
        msg: 'cookie_refresh_done',
        path: p,
        bytes: content.length
      })
    );
    return true;
  } catch (e) {
    console.error('[cookieRefresh] Failed to write cookie file:', p, e);
    return false;
  }
}

/**
 * If YT_DLP_COOKIES_FILE is set and cookies are stale, refresh them.
 * Call on worker startup and every 12h.
 */
export async function ensureFreshCookies(): Promise<void> {
  const cookiePath = config.ytDlpCookiesPath?.trim();
  if (!cookiePath) return;

  if (!isCookieStale(cookiePath)) {
    console.log(
      JSON.stringify({ msg: 'cookie_check_skipped', reason: 'cookies_still_valid', path: cookiePath })
    );
    return;
  }

  console.log(
    JSON.stringify({ msg: 'cookie_refresh_start', reason: 'stale_or_expiring', path: cookiePath })
  );
  const ok = await refreshCookies(cookiePath);
  if (!ok) {
    console.warn(JSON.stringify({ msg: 'cookie_refresh_failed', path: cookiePath }));
  }
}
