/**
 * Cookie refresh for yt-dlp: when cookies are stale (by real expiry), fetch and write.
 * Used by the worker so cookie refresh runs without the Express backend.
 */

import fs from 'node:fs';
import path from 'node:path';
import { getYtDlpCookieExpiry } from './cookieExpiry.js';
import { config } from '../config.js';

const REFRESH_BEFORE_DAYS = 2;
const DEFAULT_COOKIE_SOURCE =
  'https://raw.githubusercontent.com/ytdl-org/youtube-dl/master/youtube-dl/cookie-file.txt';
const FETCH_TIMEOUT_MS = 10_000;

function safeFirstLine(filePath: string): string | null {
  try {
    const raw = fs.readFileSync(filePath, 'utf8');
    const first = raw.split(/\r?\n/)[0] ?? '';
    const trimmed = first.trim();
    if (!trimmed) return null;
    return trimmed.length > 200 ? `${trimmed.slice(0, 200)}…` : trimmed;
  } catch {
    return null;
  }
}

function getCookieFileState(cookiePath: string): {
  path: string;
  normalizedPath: string;
  exists: boolean;
  bytes: number | null;
  firstLine: string | null;
} {
  const normalizedPath = path.normalize(cookiePath.trim());
  let exists = false;
  let bytes: number | null = null;
  let firstLine: string | null = null;
  try {
    if (fs.existsSync(normalizedPath)) {
      exists = true;
      bytes = fs.statSync(normalizedPath).size;
      firstLine = safeFirstLine(normalizedPath);
    }
  } catch {
    // ignore
  }
  return { path: cookiePath, normalizedPath, exists, bytes, firstLine };
}

function minimalNetscapeCookies(): string {
  return `# Netscape HTTP Cookie File
# Generated by BatchTube cookie refresh (placeholder - replace with browser export for age-restricted)

`;
}

/**
 * Download cookie file from a URL and write to cookiePath.
 * Used when COOKIES_INIT_URL is set and file is missing (e.g. first deploy on Railway).
 */
async function downloadCookiesFromUrl(cookiePath: string, url: string): Promise<boolean> {
  const p = path.normalize(cookiePath.trim());
  const dir = path.dirname(p);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch (e) {
    console.error('[cookieRefresh] Failed to create cookie dir:', dir, e);
    return false;
  }
  const startedAt = Date.now();
  console.log(
    JSON.stringify({
      msg: 'cookie_download_start',
      url,
      path: cookiePath,
      normalized_path: p
    })
  );
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    const res = await fetch(url, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; BatchTube/1.0)' },
      signal: controller.signal
    });
    clearTimeout(timeoutId);
    if (!res.ok) {
      console.warn('[cookieRefresh] COOKIES_INIT_URL responded', res.status);
      return false;
    }
    const content = await res.text();
    if (!content || content.length < 50) {
      console.warn('[cookieRefresh] COOKIES_INIT_URL content too short');
      return false;
    }
    fs.writeFileSync(p, content, 'utf8');
    const state = getCookieFileState(p);
    console.log(
      JSON.stringify({
        msg: 'cookie_download_done',
        url,
        path: p,
        bytes_written: content.length,
        duration_ms: Date.now() - startedAt,
        file_exists: state.exists,
        file_bytes: state.bytes,
        file_first_line: state.firstLine
      })
    );
    return true;
  } catch (e) {
    console.error('[cookieRefresh] COOKIES_INIT_URL fetch failed:', (e as Error).message);
    return false;
  } finally {
    const state = getCookieFileState(p);
    console.log(
      JSON.stringify({
        msg: 'cookie_download_state',
        url,
        path: p,
        file_exists: state.exists,
        file_bytes: state.bytes,
        file_first_line: state.firstLine
      })
    );
  }
}

/**
 * True if cookie file is missing, expired, or expiring within REFRESH_BEFORE_DAYS.
 * When expiry cannot be determined (e.g. session cookies), we do NOT treat as stale
 * so we never overwrite real user cookies with the template.
 */
export function isCookieStale(cookiePath: string): boolean {
  const p = cookiePath?.trim();
  if (!p) return false;
  if (!fs.existsSync(path.normalize(p))) return true; // missing: safe to write template
  const info = getYtDlpCookieExpiry(p);
  if (!info) return false; // unknown expiry: do not overwrite (may be real session cookies)
  if (info.isExpired) return true;
  if (info.expiresInDays <= REFRESH_BEFORE_DAYS) return true;
  return false;
}

/**
 * Fetch cookie content from URL or generate minimal. Write to cookiePath.
 */
export async function refreshCookies(cookiePath: string): Promise<boolean> {
  const p = path.normalize(cookiePath.trim());
  const dir = path.dirname(p);
  try {
    fs.mkdirSync(dir, { recursive: true });
  } catch (e) {
    console.error('[cookieRefresh] Failed to create cookie dir:', dir, e);
    return false;
  }

  const source = process.env.COOKIE_REFRESH_URL?.trim() || DEFAULT_COOKIE_SOURCE;
  let content: string;

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
    const res = await fetch(source, {
      headers: { 'User-Agent': 'Mozilla/5.0 (compatible; BatchTube/1.0)' },
      signal: controller.signal
    });
    clearTimeout(timeoutId);
    if (res.ok) {
      const text = await res.text();
      if (text && text.length > 100) content = text;
      else content = minimalNetscapeCookies();
    } else {
      content = minimalNetscapeCookies();
    }
  } catch (e) {
    console.warn('[cookieRefresh] Fetch failed, writing minimal:', (e as Error).message);
    content = minimalNetscapeCookies();
  }

  try {
    fs.writeFileSync(p, content, 'utf8');
    console.log(
      JSON.stringify({
        msg: 'cookie_refresh_done',
        path: p,
        bytes: content.length
      })
    );
    return true;
  } catch (e) {
    console.error('[cookieRefresh] Failed to write cookie file:', p, e);
    return false;
  }
}

/**
 * If YT_DLP_COOKIES_FILE is set and cookies are stale, refresh them.
 * Call on worker startup and every 12h.
 */
export async function ensureFreshCookies(): Promise<void> {
  const cookiePath = config.ytDlpCookiesPath?.trim();
  if (!cookiePath) return;

  const normalizedPath = path.normalize(cookiePath);
  if (!fs.existsSync(normalizedPath)) {
    const initUrl =
      process.env.COOKIES_INIT_URL?.trim() ||
      // Back-compat / Railway naming: the rest of the worker uses YT_DLP_COOKIES_FILE, so
      // it’s reasonable to accept YT_DLP_COOKIES_URL as the init URL source too.
      process.env.YT_DLP_COOKIES_URL?.trim();
    if (initUrl) {
      console.log(
        JSON.stringify({
          msg: 'cookie_init_start',
          reason: 'file_missing',
          path: cookiePath,
          url: initUrl,
          url_source: process.env.COOKIES_INIT_URL?.trim() ? 'COOKIES_INIT_URL' : 'YT_DLP_COOKIES_URL',
          hint: 'Downloading from COOKIES_INIT_URL (first deploy or after clean deploy).'
        })
      );
      const ok = await downloadCookiesFromUrl(cookiePath, initUrl);
      if (!ok) console.warn(JSON.stringify({ msg: 'cookie_init_failed', path: cookiePath }));
      return;
    }
    console.log(
      JSON.stringify({
        msg: 'cookie_refresh_start',
        reason: 'file_missing',
        path: cookiePath,
        hint: 'Will write template; for age-restricted content set COOKIES_INIT_URL or add file to volume.'
      })
    );
    const ok = await refreshCookies(cookiePath);
    if (!ok) console.warn(JSON.stringify({ msg: 'cookie_refresh_failed', path: cookiePath }));
    return;
  }

  const info = getYtDlpCookieExpiry(cookiePath);
  if (!info) {
    const state = getCookieFileState(cookiePath);
    console.log(
      JSON.stringify({
        msg: 'cookie_check_skipped',
        reason: 'expiry_unknown',
        path: cookiePath,
        file_exists: state.exists,
        file_bytes: state.bytes,
        file_first_line: state.firstLine,
        hint: 'Cookie file exists but no YouTube/Google expiry found (e.g. session cookies). Not overwriting.'
      })
    );
    return;
  }

  if (!info.isExpired && info.expiresInDays > REFRESH_BEFORE_DAYS) {
    const state = getCookieFileState(cookiePath);
    console.log(
      JSON.stringify({
        msg: 'cookie_check_skipped',
        reason: 'cookies_still_valid',
        path: cookiePath,
        expires_in_days: info.expiresInDays,
        file_exists: state.exists,
        file_bytes: state.bytes,
        file_first_line: state.firstLine
      })
    );
    return;
  }

  console.log(
    JSON.stringify({
      msg: 'cookie_refresh_start',
      reason: 'stale_or_expiring',
      path: cookiePath,
      expires_in_days: info.expiresInDays,
      is_expired: info.isExpired
    })
  );
  const ok = await refreshCookies(cookiePath);
  if (!ok) {
    console.warn(JSON.stringify({ msg: 'cookie_refresh_failed', path: cookiePath }));
  }
}
