import { SupportedLanguage, Translations, LegalDocType, InfoDocType } from './types';

export const APP_VERSION = 'v3.6.0 (Batch Queue)';
// Use environment variable in production, fallback to relative path for Vite proxy in development
export const API_BASE_URL = import.meta.env.VITE_API_URL || '/api';

const BASE_TRANSLATIONS: Translations = {
  heroTitle: 'Batch Download. Simplified.',
  heroSubtitle: 'High-speed parallel engine. No ads. Just content.',
  searchPlaceholder: 'Search keywords or paste YouTube link...',
  searchButton: 'Search',
  pasteLink: 'Paste Link',
  singleDownload: 'Download',
  addToBatch: 'Select',
  selected: 'Selected',
  itemsSelected: 'Videos Selected',
  itemSelected: 'Video Selected',
  clearAll: 'Clear',
  downloadZip: 'Download ZIP',
  formatLabel: 'Format',
  formatShort: 'F',
  qualityLabel: 'Quality',
  qualityShort: 'Q',
  viewList: 'View List',
  readyToProcess: 'Ready to Process',
  downloading: 'Downloading...',
  processing: 'Creating ZIP...',
  completed: 'Ready for Download',
  failed: 'Operation Failed',
  saveFile: 'Save File',
  preparing: 'Preparing...',
  waiting: 'Waiting',
  success: 'Success',
  error: 'Error',
  terms: 'Terms of Use',
  privacy: 'Privacy Policy',
  cookies: 'Cookie Policy',
  legal: 'Legal Notice',
  refundPolicy: 'Refund Policy',
  howItWorks: 'How it works',
  faq: 'FAQ',
  supportedSites: 'Supported sites',
  pricing: 'Pricing',
  seePricing: 'See Pricing',
  upgrade: 'Upgrade',
  login: 'Login',
  signup: 'Sign up',
  account: 'Account',
  logout: 'Log out',
  supportedPlatformsTitle: 'Supported Platforms',
  supportedPlatformsSubtitle: 'BatchTube supports multi-platform batch downloads.',
  availabilityNote: 'Availability may vary depending on platform restrictions.',
  plansTitle: 'Plans',
  pricingSubtitle: 'Pick the plan that fits your workflow.',
  monthlyPrice: '/mo',
  freePlan: 'Free',
  proPlan: 'Pro',
  upgradeNow: 'Upgrade Now',
  currentPlan: 'Current Plan',
  upToVideosPerBatch: 'videos per batch',
  maxQuality: 'max quality',
  adsEnabled: 'Ads enabled',
  limitedDailyUsage: 'Limited daily usage',
  standardQueue: 'Standard queue',
  noAds: 'No ads',
  priorityQueue: 'Priority queue',
  fasterZip: 'Faster ZIP processing',
  retrySupport: 'Retry support',
  accountTitle: 'Account',
  accountSubtitle: 'Manage your subscription and profile details.',
  userIdLabel: 'User ID',
  emailLabel: 'Email',
  currentPlanLabel: 'Current Plan',
  planFreeLabel: 'Free Plan',
  planProLabel: 'Pro Plan',
  manageSubscription: 'Manage subscription',
  manageSubscriptionSoon: 'Customer portal will be available soon.',
  loginTitle: 'Welcome back',
  loginSubtitle: 'Sign in to manage your account and upgrades.',
  signupTitle: 'Create your account',
  signupSubtitle: 'Start free and upgrade anytime.',
  continueButton: 'Continue',
  createAccountButton: 'Create account',
  noAccountYet: 'No account yet?',
  alreadyHaveAccount: 'Already have an account?',
  upgradeForQualityTooltip: 'Upgrade to Pro for higher quality.',
  freeBatchLimitMessage: 'Free plan allows up to 3 videos per batch.',
  checkoutUnavailable: 'Checkout is currently unavailable. Please try again shortly.',
  loginToUpgrade: 'Please log in to upgrade to Pro.',
  close: 'Close',
  acceptCookies: 'Accept',
  cookieMessage: 'We use cookies to ensure the best experience on our website.',
  allRightsReserved: 'All rights reserved.',
  searchFailed: 'Search failed. Please try again.',
  noResultsFound: 'No results found. Try a different keyword, or paste a direct video URL.',
  noResultsAvailable: 'No results available',
  backToSearch: 'Back to Search',
  batchStartFailed: 'Failed to start batch download. Please try again.',
  notFoundTitle: 'Page not found',
  notFoundBody: 'This route doesn’t exist. If you typed the URL manually, double-check it. Otherwise, head back to search.',
  metadataUnavailable: 'Metadata unavailable',
  unknownChannel: 'Channel unavailable',
  noItemsSelected: 'No items selected',
  itemsLabel: 'items',
  itemLabel: 'Item',
  batchCompleted: 'Batch Completed',
  batchFailed: 'Batch Failed',
  waitingInQueue: 'Waiting in queue...',
  preparingDownload: 'Preparing download...',
  succeededLabel: 'succeeded',
  cookie: {
    message: 'BatchTube uses cookies only for site functionality and ad display.',
    accept: 'Accept',
    reject: 'Reject',
    essential: 'Essential Only',
    reset: 'Reset Cookie Preferences'
  }
};

export const TRANSLATIONS: Record<SupportedLanguage, Translations> = {
  en: BASE_TRANSLATIONS,
  es: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Descarga por Lotes. Simplificada.',
    heroSubtitle: 'Motor paralelo de alta velocidad. Sin anuncios.',
    searchPlaceholder: 'Buscar palabras clave o pegar enlace...',
    searchButton: 'Buscar',
    pasteLink: 'Pegar Enlace',
    singleDownload: 'Descargar',
    addToBatch: 'Seleccionar',
    selected: 'Seleccionado',
    itemsSelected: 'Videos Seleccionados',
    itemSelected: 'Video Seleccionado',
    clearAll: 'Borrar',
    downloadZip: 'Descargar ZIP',
    formatLabel: 'Formato',
    qualityLabel: 'Calidad',
    viewList: 'Ver Lista',
    readyToProcess: 'Listo para Procesar',
    processing: 'Creando ZIP...',
    completed: 'Listo para Descargar',
    failed: 'Operación Fallida',
    saveFile: 'Guardar Archivo',
    preparing: 'Preparando...',
    waiting: 'En espera',
    success: 'Éxito',
    error: 'Error',
    terms: 'Términos de Uso',
    privacy: 'Política de Privacidad',
    cookies: 'Política de Cookies',
    legal: 'Aviso Legal',
    refundPolicy: 'Política de Reembolso',
    howItWorks: 'Cómo funciona',
    faq: 'Preguntas frecuentes',
    supportedSites: 'Sitios compatibles',
    pricing: 'Precios',
    seePricing: 'Ver precios',
    upgrade: 'Mejorar',
    login: 'Iniciar sesión',
    signup: 'Crear cuenta',
    account: 'Cuenta',
    logout: 'Cerrar sesión',
    plansTitle: 'Planes',
    pricingSubtitle: 'Elige el plan que se adapte a tu flujo.',
    monthlyPrice: '/mes',
    freePlan: 'Gratis',
    proPlan: 'Pro',
    upgradeNow: 'Mejorar ahora',
    currentPlan: 'Plan actual',
    upToVideosPerBatch: 'videos por lote',
    maxQuality: 'calidad máxima',
    adsEnabled: 'Anuncios activados',
    limitedDailyUsage: 'Uso diario limitado',
    standardQueue: 'Cola estándar',
    noAds: 'Sin anuncios',
    priorityQueue: 'Cola prioritaria',
    fasterZip: 'Procesamiento ZIP más rápido',
    retrySupport: 'Soporte de reintentos',
    accountTitle: 'Cuenta',
    accountSubtitle: 'Administra tu suscripción y datos de perfil.',
    userIdLabel: 'ID de usuario',
    emailLabel: 'Correo electrónico',
    currentPlanLabel: 'Plan actual',
    planFreeLabel: 'Plan Gratis',
    planProLabel: 'Plan Pro',
    manageSubscription: 'Gestionar suscripción',
    manageSubscriptionSoon: 'El portal de clientes estará disponible pronto.',
    loginTitle: 'Bienvenido de nuevo',
    loginSubtitle: 'Inicia sesión para administrar tu cuenta y mejoras.',
    signupTitle: 'Crea tu cuenta',
    signupSubtitle: 'Comienza gratis y mejora cuando quieras.',
    continueButton: 'Continuar',
    createAccountButton: 'Crear cuenta',
    noAccountYet: '¿Aún no tienes cuenta?',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    checkoutUnavailable: 'El pago no está disponible ahora. Inténtalo pronto.',
    loginToUpgrade: 'Inicia sesión para mejorar a Pro.',
    supportedPlatformsTitle: 'Plataformas compatibles',
    supportedPlatformsSubtitle: 'BatchTube admite descargas por lotes en múltiples plataformas.',
    availabilityNote: 'La disponibilidad puede variar según las restricciones de la plataforma.',
    close: 'Cerrar',
    acceptCookies: 'Aceptar',
    cookieMessage: 'Usamos cookies para asegurar la mejor experiencia.',
    allRightsReserved: 'Todos los derechos reservados.',
    searchFailed: 'La búsqueda falló. Inténtalo de nuevo.',
    noResultsFound: 'No se encontraron resultados. Prueba otra palabra o pega un URL directo.',
    noResultsAvailable: 'No hay resultados disponibles',
    backToSearch: 'Volver a Buscar',
    batchStartFailed: 'No se pudo iniciar la descarga por lotes. Inténtalo de nuevo.',
    notFoundTitle: 'Página no encontrada',
    notFoundBody: 'Esta ruta no existe. Si escribiste la URL manualmente, revísala. Si no, vuelve a la búsqueda.',
    metadataUnavailable: 'Metadatos no disponibles',
    unknownChannel: 'Canal no disponible',
    noItemsSelected: 'No hay elementos seleccionados',
    itemsLabel: 'elementos',
    itemLabel: 'Elemento',
    batchCompleted: 'Lote Completado',
    batchFailed: 'Lote Fallido',
    waitingInQueue: 'Esperando en la cola...',
    preparingDownload: 'Preparando descarga...',
    succeededLabel: 'completados',
    cookie: {
      message: 'BatchTube usa cookies solo para funcionalidad del sitio y visualización de anuncios.',
      accept: 'Aceptar',
      reject: 'Rechazar',
      essential: 'Solo Esenciales',
      reset: 'Restablecer Preferencias de Cookies'
    }
  },
  fr: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Téléchargement par Lot. Simplifié.',
    heroSubtitle: 'Moteur parallèle haute vitesse. Pas de pubs.',
    searchPlaceholder: 'Rechercher ou coller un lien...',
    searchButton: 'Chercher',
    itemsSelected: 'Vidéos sélectionnées',
    itemSelected: 'Vidéo sélectionnée',
    downloadZip: 'Télécharger ZIP',
    formatLabel: 'Format',
    qualityLabel: 'Qualité',
    viewList: 'Voir la Liste',
    readyToProcess: 'Prêt à Traiter',
    processing: 'Création du ZIP...',
    completed: 'Prêt à télécharger',
    failed: 'Échec de l’opération',
    saveFile: 'Enregistrer',
    preparing: 'Préparation...',
    waiting: 'En attente',
    success: 'Succès',
    error: 'Erreur',
    terms: "Conditions d'utilisation",
    privacy: 'Politique de confidentialité',
    cookies: 'Politique de cookies',
    legal: 'Mentions légales',
    refundPolicy: 'Politique de Remboursement',
    howItWorks: 'Comment ça marche',
    faq: 'FAQ',
    supportedSites: 'Sites pris en charge',
    pricing: 'Tarifs',
    seePricing: 'Voir les tarifs',
    upgrade: 'Passer Pro',
    login: 'Connexion',
    signup: 'Inscription',
    account: 'Compte',
    logout: 'Déconnexion',
    plansTitle: 'Formules',
    pricingSubtitle: 'Choisissez la formule adaptée à votre usage.',
    monthlyPrice: '/mois',
    freePlan: 'Gratuit',
    proPlan: 'Pro',
    upgradeNow: 'Passer à Pro',
    currentPlan: 'Formule actuelle',
    upToVideosPerBatch: 'vidéos par lot',
    maxQuality: 'qualité maximale',
    adsEnabled: 'Publicités activées',
    limitedDailyUsage: 'Utilisation quotidienne limitée',
    standardQueue: 'File standard',
    noAds: 'Sans publicité',
    priorityQueue: 'File prioritaire',
    fasterZip: 'Traitement ZIP plus rapide',
    retrySupport: 'Support des relances',
    accountTitle: 'Compte',
    accountSubtitle: 'Gérez votre abonnement et votre profil.',
    userIdLabel: 'ID utilisateur',
    emailLabel: 'E-mail',
    currentPlanLabel: 'Formule actuelle',
    planFreeLabel: 'Formule Gratuite',
    planProLabel: 'Formule Pro',
    manageSubscription: "Gérer l'abonnement",
    manageSubscriptionSoon: 'Le portail client sera bientôt disponible.',
    loginTitle: 'Bon retour',
    loginSubtitle: 'Connectez-vous pour gérer votre compte et vos upgrades.',
    signupTitle: 'Créer votre compte',
    signupSubtitle: 'Commencez gratuitement et passez Pro à tout moment.',
    continueButton: 'Continuer',
    createAccountButton: 'Créer un compte',
    noAccountYet: "Pas encore de compte ?",
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    checkoutUnavailable: 'Le paiement est indisponible pour le moment. Réessayez bientôt.',
    loginToUpgrade: 'Connectez-vous pour passer à Pro.',
    supportedPlatformsTitle: 'Plateformes prises en charge',
    supportedPlatformsSubtitle: 'BatchTube prend en charge les téléchargements par lot multi-plateformes.',
    availabilityNote: 'La disponibilité peut varier selon les restrictions des plateformes.',
    close: 'Fermer',
    acceptCookies: 'Accepter',
    cookieMessage: 'Nous utilisons des cookies pour garantir la meilleure expérience.',
    allRightsReserved: 'Tous droits réservés.',
    searchFailed: 'La recherche a échoué. Veuillez réessayer.',
    noResultsFound: 'Aucun résultat. Essayez un autre mot-clé ou collez un lien direct.',
    noResultsAvailable: 'Aucun résultat disponible',
    backToSearch: 'Retour à la Recherche',
    batchStartFailed: 'Échec du démarrage du téléchargement par lot. Veuillez réessayer.',
    notFoundTitle: 'Page introuvable',
    notFoundBody: 'Cette route n’existe pas. Si vous avez saisi l’URL manuellement, vérifiez-la. Sinon, revenez à la recherche.',
    metadataUnavailable: 'Métadonnées indisponibles',
    unknownChannel: 'Chaîne indisponible',
    noItemsSelected: 'Aucun élément sélectionné',
    itemsLabel: 'éléments',
    itemLabel: 'Élément',
    batchCompleted: 'Lot Terminé',
    batchFailed: 'Lot Échoué',
    waitingInQueue: 'En attente dans la file...',
    preparingDownload: 'Préparation du téléchargement...',
    succeededLabel: 'réussis',
    cookie: {
      message: "BatchTube utilise des cookies uniquement pour la fonctionnalité du site et l'affichage des publicités.",
      accept: 'Accepter',
      reject: 'Refuser',
      essential: 'Essentiels Seulement',
      reset: 'Réinitialiser les Préférences de Cookies'
    }
  },
  de: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Batch-Download. Vereinfacht.',
    heroSubtitle: 'Hochgeschwindigkeits-Parallel-Engine.',
    searchPlaceholder: 'Suchen oder Link einfügen...',
    searchButton: 'Suchen',
    itemsSelected: 'Videos ausgewählt',
    itemSelected: 'Video ausgewählt',
    downloadZip: 'ZIP herunterladen',
    formatLabel: 'Format',
    qualityLabel: 'Qualität',
    viewList: 'Liste Anzeigen',
    readyToProcess: 'Bereit zur Verarbeitung',
    processing: 'Erstelle ZIP...',
    completed: 'Bereit zum Download',
    failed: 'Vorgang fehlgeschlagen',
    saveFile: 'Datei speichern',
    preparing: 'Vorbereiten...',
    waiting: 'Warten',
    success: 'Erfolg',
    error: 'Fehler',
    terms: 'Nutzungsbedingungen',
    privacy: 'Datenschutz',
    cookies: 'Cookie-Richtlinie',
    legal: 'Rechtliche Hinweise',
    refundPolicy: 'Rückerstattungsrichtlinie',
    howItWorks: 'So funktioniert es',
    faq: 'FAQ',
    supportedSites: 'Unterstützte Seiten',
    pricing: 'Preise',
    seePricing: 'Preise ansehen',
    upgrade: 'Upgrade',
    login: 'Anmelden',
    signup: 'Registrieren',
    account: 'Konto',
    logout: 'Abmelden',
    plansTitle: 'Pläne',
    pricingSubtitle: 'Wähle den passenden Plan für deinen Workflow.',
    monthlyPrice: '/Monat',
    freePlan: 'Kostenlos',
    proPlan: 'Pro',
    upgradeNow: 'Jetzt upgraden',
    currentPlan: 'Aktueller Plan',
    upToVideosPerBatch: 'Videos pro Batch',
    maxQuality: 'max. Qualität',
    adsEnabled: 'Werbung aktiviert',
    limitedDailyUsage: 'Begrenzte tägliche Nutzung',
    standardQueue: 'Standard-Warteschlange',
    noAds: 'Keine Werbung',
    priorityQueue: 'Prioritäts-Warteschlange',
    fasterZip: 'Schnellere ZIP-Verarbeitung',
    retrySupport: 'Wiederholungs-Support',
    accountTitle: 'Konto',
    accountSubtitle: 'Verwalte dein Abo und deine Profildaten.',
    userIdLabel: 'Benutzer-ID',
    emailLabel: 'E-Mail',
    currentPlanLabel: 'Aktueller Plan',
    planFreeLabel: 'Free-Plan',
    planProLabel: 'Pro-Plan',
    manageSubscription: 'Abo verwalten',
    manageSubscriptionSoon: 'Das Kundenportal ist bald verfügbar.',
    loginTitle: 'Willkommen zurück',
    loginSubtitle: 'Melde dich an, um Konto und Upgrades zu verwalten.',
    signupTitle: 'Konto erstellen',
    signupSubtitle: 'Kostenlos starten und jederzeit upgraden.',
    continueButton: 'Weiter',
    createAccountButton: 'Konto erstellen',
    noAccountYet: 'Noch kein Konto?',
    alreadyHaveAccount: 'Schon ein Konto?',
    checkoutUnavailable: 'Checkout ist derzeit nicht verfügbar. Bitte später erneut versuchen.',
    loginToUpgrade: 'Bitte melde dich an, um auf Pro upzugraden.',
    supportedPlatformsTitle: 'Unterstützte Plattformen',
    supportedPlatformsSubtitle: 'BatchTube unterstützt plattformübergreifende Batch-Downloads.',
    availabilityNote: 'Die Verfügbarkeit kann je nach Plattformbeschränkungen variieren.',
    close: 'Schließen',
    acceptCookies: 'Akzeptieren',
    cookieMessage: 'Wir verwenden Cookies, um das beste Erlebnis zu gewährleisten.',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    searchFailed: 'Suche fehlgeschlagen. Bitte erneut versuchen.',
    noResultsFound: 'Keine Ergebnisse. Anderes Stichwort oder direkten Link verwenden.',
    noResultsAvailable: 'Keine Ergebnisse verfügbar',
    backToSearch: 'Zurück zur Suche',
    batchStartFailed: 'Start des Batch-Downloads fehlgeschlagen. Bitte erneut versuchen.',
    notFoundTitle: 'Seite nicht gefunden',
    notFoundBody: 'Diese Route existiert nicht. Wenn du die URL manuell eingegeben hast, überprüfe sie. Andernfalls gehe zurück zur Suche.',
    metadataUnavailable: 'Metadaten nicht verfügbar',
    unknownChannel: 'Kanal nicht verfügbar',
    noItemsSelected: 'Keine Elemente ausgewählt',
    itemsLabel: 'Elemente',
    itemLabel: 'Element',
    batchCompleted: 'Batch abgeschlossen',
    batchFailed: 'Batch fehlgeschlagen',
    waitingInQueue: 'Warten in der Warteschlange...',
    preparingDownload: 'Download wird vorbereitet...',
    succeededLabel: 'erfolgreich',
    cookie: {
      message: 'BatchTube verwendet Cookies nur für Website-Funktionalität und Anzeigen.',
      accept: 'Akzeptieren',
      reject: 'Ablehnen',
      essential: 'Nur Notwendige',
      reset: 'Cookie-Einstellungen Zurücksetzen'
    }
  },
  tr: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Toplu İndirme. Basitleştirildi.',
    heroSubtitle: 'Yüksek hızlı paralel motor. Reklamsız.',
    searchPlaceholder: 'Anahtar kelime ara veya link yapıştır...',
    searchButton: 'Ara',
    pasteLink: 'Link Yapıştır',
    singleDownload: 'İndir',
    addToBatch: 'Seç',
    selected: 'Seçildi',
    itemsSelected: 'Video Seçildi',
    itemSelected: 'Video Seçildi',
    clearAll: 'Temizle',
    downloadZip: 'ZIP İndir',
    formatLabel: 'Format',
    qualityLabel: 'Kalite',
    viewList: 'Listeyi Gör',
    readyToProcess: 'İşleme hazır',
    processing: 'ZIP Oluşturuluyor...',
    downloading: 'İndiriliyor',
    completed: 'İndirme Hazır',
    failed: 'Hata',
    preparing: 'Hazırlanıyor...',
    waiting: 'Bekleniyor',
    success: 'Başarılı',
    error: 'Hata',
    saveFile: 'Cihaza Kaydet',
    terms: 'Kullanım Şartları',
    privacy: 'Gizlilik Politikası',
    cookies: 'Çerez Politikası',
    legal: 'Yasal Uyarı',
    refundPolicy: 'İade Politikası',
    howItWorks: 'Nasıl çalışır',
    faq: 'SSS',
    supportedSites: 'Desteklenen siteler',
    pricing: 'Fiyatlandırma',
    seePricing: 'Fiyatları Gör',
    upgrade: 'Yükselt',
    login: 'Giriş',
    signup: 'Kayıt Ol',
    account: 'Hesap',
    logout: 'Çıkış',
    plansTitle: 'Planlar',
    pricingSubtitle: 'Kullanımına uygun planı seç.',
    monthlyPrice: '/ay',
    freePlan: 'Ücretsiz',
    proPlan: 'Pro',
    upgradeNow: 'Şimdi Yükselt',
    currentPlan: 'Mevcut Plan',
    upToVideosPerBatch: 'video / toplu işlem',
    maxQuality: 'maksimum kalite',
    adsEnabled: 'Reklamlar açık',
    limitedDailyUsage: 'Günlük kullanım sınırlı',
    standardQueue: 'Standart kuyruk',
    noAds: 'Reklamsız',
    priorityQueue: 'Öncelikli kuyruk',
    fasterZip: 'Daha hızlı ZIP işleme',
    retrySupport: 'Tekrar deneme desteği',
    accountTitle: 'Hesap',
    accountSubtitle: 'Aboneliğini ve profil bilgilerini yönet.',
    userIdLabel: 'Kullanıcı ID',
    emailLabel: 'E-posta',
    currentPlanLabel: 'Mevcut Plan',
    planFreeLabel: 'Ücretsiz Plan',
    planProLabel: 'Pro Plan',
    manageSubscription: 'Aboneliği Yönet',
    manageSubscriptionSoon: 'Müşteri portalı yakında aktif olacak.',
    loginTitle: 'Tekrar hoş geldin',
    loginSubtitle: 'Hesabını ve yükseltmeleri yönetmek için giriş yap.',
    signupTitle: 'Hesap oluştur',
    signupSubtitle: 'Ücretsiz başla, istediğin zaman Proya geç.',
    continueButton: 'Devam Et',
    createAccountButton: 'Hesap Oluştur',
    noAccountYet: 'Hesabın yok mu?',
    alreadyHaveAccount: 'Zaten hesabın var mı?',
    checkoutUnavailable: 'Ödeme şu anda kullanılamıyor. Lütfen biraz sonra tekrar dene.',
    loginToUpgrade: 'Proya yükseltmek için giriş yap.',
    supportedPlatformsTitle: 'Desteklenen Platformlar',
    supportedPlatformsSubtitle: 'BatchTube çoklu platform toplu indirmeyi destekler.',
    availabilityNote: 'Erişilebilirlik platform kısıtlamalarına göre değişebilir.',
    close: 'Kapat',
    acceptCookies: 'Kabul Et',
    cookieMessage: 'En iyi deneyimi sağlamak için çerezleri kullanıyoruz.',
    allRightsReserved: 'Tüm hakları saklıdır.',
    searchFailed: 'Arama başarısız. Lütfen tekrar deneyin.',
    noResultsFound: 'Sonuç bulunamadı. Başka bir kelime deneyin veya URL yapıştırın.',
    noResultsAvailable: 'Sonuç yok',
    backToSearch: 'Aramaya Dön',
    batchStartFailed: 'Toplu indirme başlatılamadı. Lütfen tekrar deneyin.',
    notFoundTitle: 'Sayfa bulunamadı',
    notFoundBody: 'Bu adres yok. URL’yi manuel yazdıysan kontrol et. Aksi halde aramaya dön.',
    metadataUnavailable: 'Meta veriler mevcut değil',
    unknownChannel: 'Kanal bilgisi yok',
    noItemsSelected: 'Seçili öğe yok',
    itemsLabel: 'öğe',
    itemLabel: 'Öğe',
    batchCompleted: 'Toplu İndirme Tamamlandı',
    batchFailed: 'Toplu İndirme Başarısız',
    waitingInQueue: 'Kuyrukta bekleniyor...',
    preparingDownload: 'İndirme hazırlanıyor...',
    succeededLabel: 'tamamlandı',
    cookie: {
      message: 'BatchTube çerezleri yalnızca site işlevselliği ve reklam gösterimi için kullanır.',
      accept: 'Kabul Et',
      reject: 'Reddet',
      essential: 'Sadece Gerekli',
      reset: 'Çerez Tercihlerini Sıfırla'
    }
  },
  pt: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Download em Lote. Simplificado.',
    heroSubtitle: 'Motor paralelo de alta velocidade.',
    searchPlaceholder: 'Pesquisar ou colar link...',
    searchButton: 'Buscar',
    itemsSelected: 'Vídeos Selecionados',
    itemSelected: 'Vídeo Selecionado',
    downloadZip: 'Baixar ZIP',
    formatLabel: 'Formato',
    qualityLabel: 'Qualidade',
    viewList: 'Ver Lista',
    readyToProcess: 'Pronto para Processar',
    processing: 'Criando ZIP...',
    completed: 'Pronto para Baixar',
    failed: 'Falha na Operação',
    saveFile: 'Salvar Arquivo',
    preparing: 'Preparando...',
    waiting: 'Aguardando',
    success: 'Sucesso',
    error: 'Erro',
    terms: 'Termos de Uso',
    privacy: 'Privacidade',
    cookies: 'Cookies',
    legal: 'Aviso Legal',
    refundPolicy: 'Política de Reembolso',
    howItWorks: 'Como funciona',
    faq: 'Perguntas frequentes',
    supportedSites: 'Sites suportados',
    pricing: 'Preços',
    seePricing: 'Ver preços',
    upgrade: 'Fazer upgrade',
    login: 'Entrar',
    signup: 'Criar conta',
    account: 'Conta',
    logout: 'Sair',
    plansTitle: 'Planos',
    pricingSubtitle: 'Escolha o plano ideal para seu fluxo.',
    monthlyPrice: '/mês',
    freePlan: 'Grátis',
    proPlan: 'Pro',
    upgradeNow: 'Fazer upgrade',
    currentPlan: 'Plano atual',
    upToVideosPerBatch: 'vídeos por lote',
    maxQuality: 'qualidade máxima',
    adsEnabled: 'Anúncios ativados',
    limitedDailyUsage: 'Uso diário limitado',
    standardQueue: 'Fila padrão',
    noAds: 'Sem anúncios',
    priorityQueue: 'Fila prioritária',
    fasterZip: 'Processamento ZIP mais rápido',
    retrySupport: 'Suporte a tentativas',
    accountTitle: 'Conta',
    accountSubtitle: 'Gerencie sua assinatura e dados do perfil.',
    userIdLabel: 'ID do usuário',
    emailLabel: 'E-mail',
    currentPlanLabel: 'Plano atual',
    planFreeLabel: 'Plano Grátis',
    planProLabel: 'Plano Pro',
    manageSubscription: 'Gerenciar assinatura',
    manageSubscriptionSoon: 'O portal do cliente estará disponível em breve.',
    loginTitle: 'Bem-vindo de volta',
    loginSubtitle: 'Entre para gerenciar sua conta e upgrades.',
    signupTitle: 'Crie sua conta',
    signupSubtitle: 'Comece grátis e faça upgrade quando quiser.',
    continueButton: 'Continuar',
    createAccountButton: 'Criar conta',
    noAccountYet: 'Ainda não tem conta?',
    alreadyHaveAccount: 'Já tem conta?',
    checkoutUnavailable: 'Checkout indisponível no momento. Tente novamente em breve.',
    loginToUpgrade: 'Faça login para fazer upgrade para Pro.',
    supportedPlatformsTitle: 'Plataformas suportadas',
    supportedPlatformsSubtitle: 'BatchTube oferece suporte a downloads em lote multi-plataforma.',
    availabilityNote: 'A disponibilidade pode variar dependendo das restrições da plataforma.',
    close: 'Fechar',
    acceptCookies: 'Aceitar',
    cookieMessage: 'Usamos cookies para garantir a melhor experiência.',
    allRightsReserved: 'Todos os direitos reservados.',
    searchFailed: 'A busca falhou. Tente novamente.',
    noResultsFound: 'Nenhum resultado. Tente outra palavra ou cole um link direto.',
    noResultsAvailable: 'Nenhum resultado disponível',
    backToSearch: 'Voltar à Busca',
    batchStartFailed: 'Falha ao iniciar o download em lote. Tente novamente.',
    notFoundTitle: 'Página não encontrada',
    notFoundBody: 'Esta rota não existe. Se você digitou a URL manualmente, verifique-a. Caso contrário, volte à busca.',
    metadataUnavailable: 'Metadados indisponíveis',
    unknownChannel: 'Canal indisponível',
    noItemsSelected: 'Nenhum item selecionado',
    itemsLabel: 'itens',
    itemLabel: 'Item',
    batchCompleted: 'Lote Concluído',
    batchFailed: 'Lote Falhou',
    waitingInQueue: 'Aguardando na fila...',
    preparingDownload: 'Preparando download...',
    succeededLabel: 'concluídos',
    cookie: {
      message: 'BatchTube usa cookies apenas para funcionalidade do site e exibição de anúncios.',
      accept: 'Aceitar',
      reject: 'Rejeitar',
      essential: 'Apenas Essenciais',
      reset: 'Redefinir Preferências de Cookies'
    }
  },
  ar: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'تحميل جماعي. مبسط.',
    heroSubtitle: 'محرك متوازي عالي السرعة. بدون إعلانات.',
    searchPlaceholder: 'بحث أو لصق الرابط...',
    searchButton: 'بحث',
    pasteLink: 'لصق الرابط',
    singleDownload: 'تحميل',
    addToBatch: 'تحديد',
    selected: 'محدد',
    itemsSelected: 'فيديو محدد',
    itemSelected: 'فيديو محدد',
    clearAll: 'مسح',
    downloadZip: 'تحميل ZIP',
    formatLabel: 'التنسيق',
    qualityLabel: 'الجودة',
    viewList: 'عرض القائمة',
    readyToProcess: 'جاهز للمعالجة',
    processing: 'جاري إنشاء ZIP...',
    completed: 'جاهز للتحميل',
    saveFile: 'حفظ الملف',
    failed: 'فشل العملية',
    preparing: 'جارٍ التحضير...',
    waiting: 'انتظار',
    success: 'نجاح',
    error: 'خطأ',
    terms: 'شروط الاستخدام',
    privacy: 'سياسة الخصوصية',
    cookies: 'سياسة ملفات تعريف الارتباط',
    legal: 'إشعار قانوني',
    refundPolicy: 'سياسة الاسترداد',
    howItWorks: 'كيف يعمل',
    faq: 'الأسئلة الشائعة',
    supportedSites: 'المواقع المدعومة',
    pricing: 'الأسعار',
    seePricing: 'عرض الأسعار',
    upgrade: 'ترقية',
    login: 'تسجيل الدخول',
    signup: 'إنشاء حساب',
    account: 'الحساب',
    logout: 'تسجيل الخروج',
    plansTitle: 'الخطط',
    pricingSubtitle: 'اختر الخطة المناسبة لسير عملك.',
    monthlyPrice: '/شهريًا',
    freePlan: 'مجاني',
    proPlan: 'برو',
    upgradeNow: 'الترقية الآن',
    currentPlan: 'الخطة الحالية',
    upToVideosPerBatch: 'فيديو لكل دفعة',
    maxQuality: 'أقصى جودة',
    adsEnabled: 'الإعلانات مفعلة',
    limitedDailyUsage: 'استخدام يومي محدود',
    standardQueue: 'طابور قياسي',
    noAds: 'بدون إعلانات',
    priorityQueue: 'طابور أولوية',
    fasterZip: 'معالجة ZIP أسرع',
    retrySupport: 'دعم إعادة المحاولة',
    accountTitle: 'الحساب',
    accountSubtitle: 'إدارة الاشتراك وبيانات الحساب.',
    userIdLabel: 'معرّف المستخدم',
    emailLabel: 'البريد الإلكتروني',
    currentPlanLabel: 'الخطة الحالية',
    planFreeLabel: 'الخطة المجانية',
    planProLabel: 'خطة برو',
    manageSubscription: 'إدارة الاشتراك',
    manageSubscriptionSoon: 'بوابة العملاء ستكون متاحة قريبًا.',
    loginTitle: 'مرحبًا بعودتك',
    loginSubtitle: 'سجّل الدخول لإدارة الحساب والترقية.',
    signupTitle: 'إنشاء حساب',
    signupSubtitle: 'ابدأ مجانًا وقم بالترقية في أي وقت.',
    continueButton: 'متابعة',
    createAccountButton: 'إنشاء الحساب',
    noAccountYet: 'ليس لديك حساب بعد؟',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    checkoutUnavailable: 'الدفع غير متاح حاليًا. حاول مرة أخرى لاحقًا.',
    loginToUpgrade: 'يرجى تسجيل الدخول للترقية إلى برو.',
    supportedPlatformsTitle: 'المنصات المدعومة',
    supportedPlatformsSubtitle: 'يدعم BatchTube التنزيلات الدفعية متعددة المنصات.',
    availabilityNote: 'قد يختلف التوفر حسب قيود المنصة.',
    close: 'إغلاق',
    acceptCookies: 'قبول',
    cookieMessage: 'نحن نستخدم ملفات تعريف الارتباط لضمان أفضل تجربة.',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    searchFailed: 'فشل البحث. حاول مرة أخرى.',
    noResultsFound: 'لا توجد نتائج. جرّب كلمة أخرى أو الصق رابطًا مباشرًا.',
    noResultsAvailable: 'لا توجد نتائج',
    backToSearch: 'العودة للبحث',
    batchStartFailed: 'تعذر بدء التنزيل الجماعي. حاول مرة أخرى.',
    notFoundTitle: 'الصفحة غير موجودة',
    notFoundBody: 'هذا المسار غير موجود. إذا كتبت الرابط يدويًا فتأكد منه. وإلا فارجع إلى البحث.',
    metadataUnavailable: 'البيانات غير متوفرة',
    unknownChannel: 'القناة غير متوفرة',
    noItemsSelected: 'لا توجد عناصر محددة',
    itemsLabel: 'عناصر',
    itemLabel: 'عنصر',
    batchCompleted: 'اكتمل التنزيل الجماعي',
    batchFailed: 'فشل التنزيل الجماعي',
    waitingInQueue: 'الانتظار في الطابور...',
    preparingDownload: 'جارٍ تجهيز التنزيل...',
    succeededLabel: 'تم',
    cookie: {
      message: 'BatchTube يستخدم ملفات تعريف الارتباط فقط لوظائف الموقع وعرض الإعلانات.',
      accept: 'قبول',
      reject: 'رفض',
      essential: 'الأساسية فقط',
      reset: 'إعادة تعيين تفضيلات ملفات تعريف الارتباط'
    }
  }
};

export const LEGAL_TEXTS: Record<SupportedLanguage, Record<LegalDocType, string>> = {
  en: {
    terms: `BatchTube Terms of Service\n\n1. Acceptance\nBy using BatchTube, you agree to these terms.\n\n2. Usage\nThis tool is for personal, educational use only. You must comply with YouTube's Terms of Service.\n\n3. Liability\nBatchTube is not responsible for copyright infringement caused by users.`,
    privacy: `Privacy Policy\n\n1. Data Collection\nWe do not store user data permanently. Download logs are cleared regularly.\n\n2. Third Parties\nWe use Google AdSense which may collect anonymous usage data.`,
    cookies: `Cookie Policy\n\nWe use essential cookies to manage your session and preferences. AdSense uses cookies to serve relevant ads.`,
    legal: `Legal Notice\n\nBatchTube is not affiliated with Google LLC or YouTube. All trademarks belong to their respective owners.`,
    refund: `Refund Policy\n\n1. Subscription Billing\nPro plans are billed monthly and renew automatically unless canceled.\n\n2. Refund Eligibility\nIf you were charged by mistake or experienced a billing issue, contact support within 7 days of the charge.\n\n3. Non-refundable Cases\nPartial-month usage and normal service usage are generally non-refundable.\n\n4. Cancellation\nYou can cancel renewal anytime from your account billing settings.`
  },
  es: {
    terms: `Términos de Servicio de BatchTube\n\n1. Aceptación\nAl usar BatchTube, aceptas estos términos.\n\n2. Uso\nEsta herramienta es solo para uso personal y educativo. Debes cumplir con los Términos de Servicio de YouTube.\n\n3. Responsabilidad\nBatchTube no es responsable de infracciones de copyright causadas por los usuarios.`,
    privacy: `Política de Privacidad\n\n1. Recolección de datos\nNo almacenamos datos de usuario de forma permanente. Los registros de descarga se eliminan regularmente.\n\n2. Terceros\nUsamos Google AdSense, que puede recopilar datos de uso anónimos.`,
    cookies: `Política de Cookies\n\nUsamos cookies esenciales para gestionar tu sesión y preferencias. AdSense usa cookies para anuncios relevantes.`,
    legal: `Aviso Legal\n\nBatchTube no está afiliado con Google LLC ni YouTube. Todas las marcas pertenecen a sus propietarios.`,
    refund: `Política de Reembolso\n\n1. Facturación de suscripción\nLos planes Pro se cobran mensualmente y se renuevan automáticamente salvo cancelación.\n\n2. Elegibilidad de reembolso\nSi hubo un cobro por error o un problema de facturación, contacta soporte dentro de 7 días desde el cobro.\n\n3. Casos no reembolsables\nEl uso normal del servicio y períodos parciales generalmente no son reembolsables.\n\n4. Cancelación\nPuedes cancelar la renovación en cualquier momento desde la configuración de facturación de tu cuenta.`
  },
  fr: {
    terms: `Conditions d'utilisation de BatchTube\n\n1. Acceptation\nEn utilisant BatchTube, vous acceptez ces conditions.\n\n2. Utilisation\nCet outil est réservé à un usage personnel et éducatif. Vous devez respecter les Conditions d'utilisation de YouTube.\n\n3. Responsabilité\nBatchTube n'est pas responsable des violations de copyright causées par les utilisateurs.`,
    privacy: `Politique de confidentialité\n\n1. Collecte des données\nNous ne stockons pas les données utilisateur de façon permanente. Les journaux de téléchargement sont supprimés régulièrement.\n\n2. Tiers\nNous utilisons Google AdSense, qui peut collecter des données d'utilisation anonymes.`,
    cookies: `Politique de cookies\n\nNous utilisons des cookies essentiels pour gérer votre session et vos préférences. AdSense utilise des cookies pour des annonces pertinentes.`,
    legal: `Mentions légales\n\nBatchTube n'est pas affilié à Google LLC ou YouTube. Toutes les marques appartiennent à leurs propriétaires.`,
    refund: `Politique de Remboursement\n\n1. Facturation de l'abonnement\nLes offres Pro sont facturées mensuellement et renouvelées automatiquement sauf annulation.\n\n2. Éligibilité au remboursement\nEn cas de facturation erronée ou de problème de paiement, contactez le support dans les 7 jours suivant le débit.\n\n3. Cas non remboursables\nL'utilisation normale du service et les périodes partielles ne sont généralement pas remboursables.\n\n4. Annulation\nVous pouvez annuler le renouvellement à tout moment depuis les paramètres de facturation de votre compte.`
  },
  de: {
    terms: `BatchTube Nutzungsbedingungen\n\n1. Akzeptanz\nDurch die Nutzung von BatchTube akzeptierst du diese Bedingungen.\n\n2. Nutzung\nDieses Tool ist nur für den persönlichen und bildungsbezogenen Gebrauch bestimmt. Du musst die YouTube-Nutzungsbedingungen einhalten.\n\n3. Haftung\nBatchTube ist nicht verantwortlich für Urheberrechtsverletzungen durch Nutzer.`,
    privacy: `Datenschutz\n\n1. Datenerhebung\nWir speichern keine Nutzerdaten dauerhaft. Download-Protokolle werden regelmäßig gelöscht.\n\n2. Drittanbieter\nWir verwenden Google AdSense, das anonyme Nutzungsdaten erfassen kann.`,
    cookies: `Cookie-Richtlinie\n\nWir verwenden essentielle Cookies zur Verwaltung deiner Sitzung und Präferenzen. AdSense verwendet Cookies für relevante Anzeigen.`,
    legal: `Rechtliche Hinweise\n\nBatchTube ist nicht mit Google LLC oder YouTube verbunden. Alle Marken gehören ihren jeweiligen Eigentümern.`,
    refund: `Rückerstattungsrichtlinie\n\n1. Abonnement-Abrechnung\nPro-Pläne werden monatlich berechnet und automatisch verlängert, sofern nicht gekündigt.\n\n2. Erstattungsberechtigung\nBei Fehlabbuchung oder Abrechnungsproblem kontaktiere den Support innerhalb von 7 Tagen nach der Belastung.\n\n3. Nicht erstattungsfähige Fälle\nNormale Nutzung und Teilmonate sind in der Regel nicht erstattungsfähig.\n\n4. Kündigung\nDu kannst die Verlängerung jederzeit in den Abrechnungseinstellungen deines Kontos kündigen.`
  },
  tr: {
    terms: `BatchTube Kullanım Şartları\n\n1. Kabul\nBatchTube'u kullanarak bu şartları kabul etmiş olursunuz.\n\n2. Kullanım\nBu araç yalnızca kişisel ve eğitim amaçlıdır. YouTube Kullanım Şartlarına uymalısınız.\n\n3. Sorumluluk\nBatchTube, kullanıcıların yaptığı telif ihlallerinden sorumlu değildir.`,
    privacy: `Gizlilik Politikası\n\n1. Veri Toplama\nKullanıcı verilerini kalıcı olarak saklamıyoruz. İndirme kayıtları düzenli olarak temizlenir.\n\n2. Üçüncü Taraflar\nGoogle AdSense kullanıyoruz; anonim kullanım verileri toplayabilir.`,
    cookies: `Çerez Politikası\n\nOturum ve tercihleri yönetmek için gerekli çerezler kullanılır. AdSense, ilgili reklamlar için çerez kullanır.`,
    legal: `Yasal Uyarı\n\nBatchTube, Google LLC veya YouTube ile bağlantılı değildir. Tüm markalar sahiplerine aittir.`,
    refund: `İade Politikası\n\n1. Abonelik Faturalandırması\nPro planlar aylık olarak ücretlendirilir ve iptal edilmediği sürece otomatik yenilenir.\n\n2. İade Uygunluğu\nYanlış ücretlendirme veya faturalandırma sorunu yaşarsanız, ödeme tarihinden itibaren 7 gün içinde destekle iletişime geçin.\n\n3. İade Yapılmayan Durumlar\nKısmi dönem kullanımı ve hizmetin normal kullanımı genellikle iade kapsamına girmez.\n\n4. İptal\nYenilemeyi hesap faturalandırma ayarlarından istediğiniz zaman iptal edebilirsiniz.`
  },
  pt: {
    terms: `Termos de Serviço do BatchTube\n\n1. Aceitação\nAo usar o BatchTube, você concorda com estes termos.\n\n2. Uso\nEsta ferramenta é apenas para uso pessoal e educacional. Você deve cumprir os Termos de Serviço do YouTube.\n\n3. Responsabilidade\nO BatchTube não é responsável por violações de direitos autorais causadas pelos usuários.`,
    privacy: `Política de Privacidade\n\n1. Coleta de dados\nNão armazenamos dados do usuário permanentemente. Os registros de download são limpos regularmente.\n\n2. Terceiros\nUsamos o Google AdSense, que pode coletar dados de uso anônimos.`,
    cookies: `Política de Cookies\n\nUsamos cookies essenciais para gerenciar sua sessão e preferências. O AdSense usa cookies para anúncios relevantes.`,
    legal: `Aviso Legal\n\nO BatchTube não é afiliado ao Google LLC ou ao YouTube. Todas as marcas pertencem aos seus proprietários.`,
    refund: `Política de Reembolso\n\n1. Cobrança de assinatura\nOs planos Pro são cobrados mensalmente e renovam automaticamente, salvo cancelamento.\n\n2. Elegibilidade de reembolso\nSe houver cobrança incorreta ou problema de faturamento, contate o suporte em até 7 dias após a cobrança.\n\n3. Casos não reembolsáveis\nUso normal do serviço e períodos parciais geralmente não são reembolsáveis.\n\n4. Cancelamento\nVocê pode cancelar a renovação a qualquer momento nas configurações de cobrança da conta.`
  },
  ar: {
    terms: `شروط استخدام BatchTube\n\n1. القبول\nباستخدام BatchTube فإنك توافق على هذه الشروط.\n\n2. الاستخدام\nهذه الأداة للاستخدام الشخصي والتعليمي فقط. يجب الالتزام بشروط خدمة YouTube.\n\n3. المسؤولية\nBatchTube غير مسؤول عن انتهاكات حقوق النشر التي يقوم بها المستخدمون.`,
    privacy: `سياسة الخصوصية\n\n1. جمع البيانات\nلا نقوم بتخزين بيانات المستخدم بشكل دائم. يتم حذف سجلات التنزيل بشكل دوري.\n\n2. أطراف ثالثة\nنستخدم Google AdSense الذي قد يجمع بيانات استخدام مجهولة.`,
    cookies: `سياسة ملفات تعريف الارتباط\n\nنستخدم ملفات تعريف الارتباط الأساسية لإدارة الجلسة والتفضيلات. يستخدم AdSense ملفات تعريف الارتباط للإعلانات المناسبة.`,
    legal: `إشعار قانوني\n\nBatchTube غير تابع لـ Google LLC أو YouTube. جميع العلامات التجارية تعود لأصحابها.`,
    refund: `سياسة الاسترداد\n\n1. فوترة الاشتراك\nيتم تحصيل رسوم خطة برو شهريًا وتتجدد تلقائيًا ما لم يتم الإلغاء.\n\n2. أهلية الاسترداد\nإذا حدثت عملية تحصيل خاطئة أو مشكلة في الفوترة، تواصل مع الدعم خلال 7 أيام من تاريخ الدفع.\n\n3. الحالات غير القابلة للاسترداد\nالاستخدام العادي للخدمة والفترات الجزئية غالبًا غير قابلة للاسترداد.\n\n4. الإلغاء\nيمكنك إيقاف التجديد في أي وقت من إعدادات فوترة الحساب.`
  }
};

export const INFO_TEXTS: Record<SupportedLanguage, Record<InfoDocType, string>> = {
  en: {
    howItWorks: `How It Works\n\n1. Paste a YouTube URL or search by keyword.\n2. Select videos and choose format/quality.\n3. Start the batch and download the ZIP when ready.`,
    faq: `FAQ\n\nQ: Is this free?\nA: Yes, it's free to use.\n\nQ: Do you store my files?\nA: No, downloads are processed temporarily.\n\nQ: Why can't I download some videos?\nA: Some videos may be restricted or unavailable.`,
    supportedSites: `Supported Sites\n\n- YouTube (videos and shorts)\n- youtu.be short links\nMore platforms may be added over time.`
  },
  es: {
    howItWorks: `Cómo funciona\n\n1. Pega un URL de YouTube o busca por palabra clave.\n2. Selecciona videos y elige formato/calidad.\n3. Inicia el lote y descarga el ZIP cuando esté listo.`,
    faq: `Preguntas frecuentes\n\nP: ¿Es gratis?\nR: Sí, es gratuito.\n\nP: ¿Guardan mis archivos?\nR: No, las descargas se procesan temporalmente.\n\nP: ¿Por qué no puedo descargar algunos videos?\nR: Algunos videos pueden estar restringidos o no disponibles.`,
    supportedSites: `Sitios compatibles\n\n- YouTube (videos y shorts)\n- Enlaces cortos youtu.be\nSe añadirán más plataformas con el tiempo.`
  },
  fr: {
    howItWorks: `Comment ça marche\n\n1. Collez un lien YouTube ou recherchez par mot-clé.\n2. Sélectionnez des vidéos et choisissez le format/la qualité.\n3. Lancez le lot et téléchargez le ZIP une fois prêt.`,
    faq: `FAQ\n\nQ : Est-ce gratuit ?\nR : Oui, c'est gratuit.\n\nQ : Stockez-vous mes fichiers ?\nR : Non, les téléchargements sont temporaires.\n\nQ : Pourquoi ne puis-je pas télécharger certaines vidéos ?\nR : Certaines vidéos peuvent être restreintes ou indisponibles.`,
    supportedSites: `Sites pris en charge\n\n- YouTube (vidéos et shorts)\n- Liens courts youtu.be\nD'autres plateformes pourront être ajoutées.`
  },
  de: {
    howItWorks: `So funktioniert es\n\n1. Füge eine YouTube-URL ein oder suche per Keyword.\n2. Wähle Videos und Format/Qualität.\n3. Starte den Batch und lade das ZIP herunter, wenn es bereit ist.`,
    faq: `FAQ\n\nF: Ist das kostenlos?\nA: Ja, es ist kostenlos.\n\nF: Speichert ihr meine Dateien?\nA: Nein, Downloads werden nur temporär verarbeitet.\n\nF: Warum kann ich einige Videos nicht herunterladen?\nA: Einige Videos können eingeschränkt oder nicht verfügbar sein.`,
    supportedSites: `Unterstützte Seiten\n\n- YouTube (Videos und Shorts)\n- youtu.be Kurzlinks\nWeitere Plattformen können später hinzugefügt werden.`
  },
  tr: {
    howItWorks: `Nasıl çalışır\n\n1. YouTube URL'si yapıştırın veya anahtar kelimeyle arayın.\n2. Videoları seçin ve format/kaliteyi belirleyin.\n3. Toplu işlemi başlatın ve hazır olduğunda ZIP'i indirin.`,
    faq: `SSS\n\nS: Ücretsiz mi?\nC: Evet, ücretsizdir.\n\nS: Dosyalarımı saklıyor musunuz?\nC: Hayır, indirmeler geçici olarak işlenir.\n\nS: Bazı videoları neden indiremem?\nC: Bazı videolar kısıtlı veya kullanılamaz olabilir.`,
    supportedSites: `Desteklenen siteler\n\n- YouTube (videolar ve shorts)\n- youtu.be kısa bağlantıları\nZamanla daha fazla platform eklenebilir.`
  },
  pt: {
    howItWorks: `Como funciona\n\n1. Cole um URL do YouTube ou pesquise por palavra-chave.\n2. Selecione vídeos e escolha formato/qualidade.\n3. Inicie o lote e baixe o ZIP quando estiver pronto.`,
    faq: `Perguntas frequentes\n\nP: É grátis?\nR: Sim, é gratuito.\n\nP: Vocês armazenam meus arquivos?\nR: Não, os downloads são processados temporariamente.\n\nP: Por que não consigo baixar alguns vídeos?\nR: Alguns vídeos podem estar restritos ou indisponíveis.`,
    supportedSites: `Sites suportados\n\n- YouTube (vídeos e shorts)\n- Links curtos youtu.be\nMais plataformas podem ser adicionadas no futuro.`
  },
  ar: {
    howItWorks: `كيف يعمل\n\n1. الصق رابط يوتيوب أو ابحث بكلمة مفتاحية.\n2. اختر المقاطع وحدد التنسيق/الجودة.\n3. ابدأ الدفعة وحمّل ملف ZIP عند الجاهزية.`,
    faq: `الأسئلة الشائعة\n\nس: هل الخدمة مجانية؟\nج: نعم، مجانية.\n\nس: هل تخزنون ملفاتي؟\nج: لا، تتم معالجة التنزيلات مؤقتًا.\n\nس: لماذا لا يمكنني تنزيل بعض المقاطع؟\nج: قد تكون بعض المقاطع مقيدة أو غير متاحة.`,
    supportedSites: `المواقع المدعومة\n\n- YouTube (فيديوهات و Shorts)\n- روابط youtu.be القصيرة\nقد تتم إضافة منصات أخرى لاحقًا.`
  }
};
