import { SupportedLanguage, Translations, LegalDocType, InfoPageType } from './types';

export const APP_VERSION = 'v3.5.0 (Parallel ZIP)';

const BASE_TRANSLATIONS: Translations = {
  heroTitle: 'Batch Download. Simplified.',
  heroSubtitle: 'High-speed parallel engine. No ads. Just content.',
  searchPlaceholder: 'Search keywords or paste YouTube link...',
  searchButton: 'Search',
  pasteLink: 'Paste Link',
  singleDownload: 'Download',
  addToBatch: 'Select',
  selected: 'Selected',
  itemsSelected: 'Videos Selected',
  itemSelected: 'Video Selected',
  clearAll: 'Clear',
  downloadZip: 'Download ZIP',
  formatLabel: 'Format',
  formatShort: 'F',
  qualityLabel: 'Quality',
  qualityShort: 'Q',
  viewList: 'View List',
  readyToProcess: 'Ready to Process',
  downloading: 'Downloading...',
  processing: 'Creating ZIP...',
  completed: 'Ready for Download',
  failed: 'Operation Failed',
  saveFile: 'Save File',
  preparing: 'Preparing...',
  waiting: 'Waiting',
  success: 'Success',
  error: 'Error',
  terms: 'Terms of Use',
  privacy: 'Privacy Policy',
  cookies: 'Cookie Policy',
  legal: 'Legal Notice',
  howItWorks: 'How it works',
  faq: 'FAQ',
  supportedSites: 'Supported sites',
  close: 'Close',
  acceptCookies: 'Accept',
  cookieMessage: 'We use cookies to ensure the best experience on our website.',
  metadataUnavailable: 'Metadata unavailable',
  noItemsSelected: 'No items selected',
  unknownChannel: 'Channel unavailable',
  remove: 'Remove',
  backToSearch: 'Back to Search',
  allRightsReserved: 'All rights reserved.',
  batchCompleted: 'Batch Completed',
  batchFailed: 'Batch Failed',
  waitingInQueue: 'Waiting in queue...',
  preparingDownload: 'Preparing download...',
  noResultsAvailable: 'No results available',
  succeededLabel: 'succeeded',
  itemsLabel: 'items',
  itemLabel: 'Item',
  cookie: {
    message: 'BatchTube uses cookies only for site functionality and ad display.',
    accept: 'Accept',
    reject: 'Reject',
    essential: 'Essential Only',
    reset: 'Reset Cookie Preferences'
  }
};

export const TRANSLATIONS: Record<SupportedLanguage, Translations> = {
  en: BASE_TRANSLATIONS,
  es: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Descarga por Lotes. Simplificada.',
    heroSubtitle: 'Motor paralelo de alta velocidad. Sin anuncios. Solo contenido.',
    searchPlaceholder: 'Buscar palabras clave o pegar enlace de YouTube...',
    searchButton: 'Buscar',
    pasteLink: 'Pegar Enlace',
    singleDownload: 'Descargar',
    addToBatch: 'Seleccionar',
    selected: 'Seleccionado',
    itemsSelected: 'Videos Seleccionados',
    itemSelected: 'Video Seleccionado',
    clearAll: 'Borrar',
    downloadZip: 'Descargar ZIP',
    formatLabel: 'Formato',
    formatShort: 'F',
    qualityLabel: 'Calidad',
    qualityShort: 'C',
    viewList: 'Ver Lista',
    readyToProcess: 'Listo para Procesar',
    downloading: 'Descargando...',
    processing: 'Creando ZIP...',
    completed: 'Listo para Descargar',
    failed: 'Operación Fallida',
    saveFile: 'Guardar Archivo',
    preparing: 'Preparando...',
    waiting: 'En espera',
    success: 'Éxito',
    error: 'Error',
    terms: 'Términos de Uso',
    privacy: 'Política de Privacidad',
    cookies: 'Política de Cookies',
    legal: 'Aviso Legal',
    howItWorks: 'Cómo funciona',
    faq: 'Preguntas frecuentes',
    supportedSites: 'Sitios compatibles',
    close: 'Cerrar',
    acceptCookies: 'Aceptar',
    cookieMessage: 'Usamos cookies para asegurar la mejor experiencia en nuestro sitio.',
    metadataUnavailable: 'Metadatos no disponibles',
    noItemsSelected: 'No hay elementos seleccionados',
    unknownChannel: 'Canal no disponible',
    remove: 'Quitar',
    backToSearch: 'Volver a Buscar',
    allRightsReserved: 'Todos los derechos reservados.',
    batchCompleted: 'Lote Completado',
    batchFailed: 'Lote Fallido',
    waitingInQueue: 'Esperando en la cola...',
    preparingDownload: 'Preparando descarga...',
    noResultsAvailable: 'No hay resultados disponibles',
    succeededLabel: 'completados',
    itemsLabel: 'elementos',
    itemLabel: 'Elemento',
    cookie: {
      message: 'BatchTube usa cookies solo para funcionalidad del sitio y visualización de anuncios.',
      accept: 'Aceptar',
      reject: 'Rechazar',
      essential: 'Solo Esenciales',
      reset: 'Restablecer Preferencias de Cookies'
    }
  },
  fr: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Téléchargement par Lot. Simplifié.',
    heroSubtitle: 'Moteur parallèle haute vitesse. Pas de pubs. Juste le contenu.',
    searchPlaceholder: 'Rechercher ou coller un lien YouTube...',
    searchButton: 'Chercher',
    pasteLink: 'Coller le lien',
    singleDownload: 'Télécharger',
    addToBatch: 'Sélectionner',
    selected: 'Sélectionné',
    itemsSelected: 'Vidéos sélectionnées',
    itemSelected: 'Vidéo sélectionnée',
    clearAll: 'Effacer',
    downloadZip: 'Télécharger ZIP',
    formatLabel: 'Format',
    formatShort: 'F',
    qualityLabel: 'Qualité',
    qualityShort: 'Q',
    viewList: 'Voir la Liste',
    readyToProcess: 'Prêt à Traiter',
    downloading: 'Téléchargement...',
    processing: 'Création du ZIP...',
    completed: 'Prêt à télécharger',
    failed: 'Échec de l’opération',
    saveFile: 'Enregistrer',
    preparing: 'Préparation...',
    waiting: 'En attente',
    success: 'Succès',
    error: 'Erreur',
    terms: "Conditions d'utilisation",
    privacy: 'Politique de confidentialité',
    cookies: 'Politique de cookies',
    legal: 'Mentions légales',
    howItWorks: 'Comment ça marche',
    faq: 'FAQ',
    supportedSites: 'Sites pris en charge',
    close: 'Fermer',
    acceptCookies: 'Accepter',
    cookieMessage: 'Nous utilisons des cookies pour garantir la meilleure expérience.',
    metadataUnavailable: 'Métadonnées indisponibles',
    noItemsSelected: 'Aucun élément sélectionné',
    unknownChannel: 'Chaîne indisponible',
    remove: 'Retirer',
    backToSearch: 'Retour à la Recherche',
    allRightsReserved: 'Tous droits réservés.',
    batchCompleted: 'Lot Terminé',
    batchFailed: 'Lot Échoué',
    waitingInQueue: "En attente dans la file...",
    preparingDownload: 'Préparation du téléchargement...',
    noResultsAvailable: 'Aucun résultat disponible',
    succeededLabel: 'réussis',
    itemsLabel: 'éléments',
    itemLabel: 'Élément',
    cookie: {
      message: "BatchTube utilise des cookies uniquement pour la fonctionnalité du site et l'affichage des publicités.",
      accept: 'Accepter',
      reject: 'Refuser',
      essential: 'Essentiels Seulement',
      reset: 'Réinitialiser les Préférences de Cookies'
    }
  },
  de: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Batch-Download. Vereinfacht.',
    heroSubtitle: 'Hochgeschwindigkeits-Parallel-Engine. Keine Werbung.',
    searchPlaceholder: 'Suchen oder YouTube-Link einfügen...',
    searchButton: 'Suchen',
    pasteLink: 'Link Einfügen',
    singleDownload: 'Herunterladen',
    addToBatch: 'Auswählen',
    selected: 'Ausgewählt',
    itemsSelected: 'Videos ausgewählt',
    itemSelected: 'Video ausgewählt',
    clearAll: 'Löschen',
    downloadZip: 'ZIP herunterladen',
    formatLabel: 'Format',
    formatShort: 'F',
    qualityLabel: 'Qualität',
    qualityShort: 'Q',
    viewList: 'Liste Anzeigen',
    readyToProcess: 'Bereit zur Verarbeitung',
    downloading: 'Wird heruntergeladen...',
    processing: 'ZIP wird erstellt...',
    completed: 'Bereit zum Download',
    failed: 'Vorgang fehlgeschlagen',
    saveFile: 'Datei speichern',
    preparing: 'Vorbereiten...',
    waiting: 'Warten',
    success: 'Erfolg',
    error: 'Fehler',
    terms: 'Nutzungsbedingungen',
    privacy: 'Datenschutz',
    cookies: 'Cookie-Richtlinie',
    legal: 'Rechtliche Hinweise',
    howItWorks: 'So funktioniert es',
    faq: 'FAQ',
    supportedSites: 'Unterstützte Seiten',
    close: 'Schließen',
    acceptCookies: 'Akzeptieren',
    cookieMessage: 'Wir verwenden Cookies, um das beste Erlebnis zu gewährleisten.',
    metadataUnavailable: 'Metadaten nicht verfügbar',
    noItemsSelected: 'Keine Elemente ausgewählt',
    unknownChannel: 'Kanal nicht verfügbar',
    remove: 'Entfernen',
    backToSearch: 'Zurück zur Suche',
    allRightsReserved: 'Alle Rechte vorbehalten.',
    batchCompleted: 'Batch abgeschlossen',
    batchFailed: 'Batch fehlgeschlagen',
    waitingInQueue: 'Warten in der Warteschlange...',
    preparingDownload: 'Download wird vorbereitet...',
    noResultsAvailable: 'Keine Ergebnisse verfügbar',
    succeededLabel: 'erfolgreich',
    itemsLabel: 'Elemente',
    itemLabel: 'Element',
    cookie: {
      message: 'BatchTube verwendet Cookies nur für Website-Funktionalität und Anzeigen.',
      accept: 'Akzeptieren',
      reject: 'Ablehnen',
      essential: 'Nur Notwendige',
      reset: 'Cookie-Einstellungen Zurücksetzen'
    }
  },
  tr: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Toplu İndirme. Basitleştirildi.',
    heroSubtitle: 'Yüksek hızlı paralel motor. Reklamsız. Sadece içerik.',
    searchPlaceholder: 'Anahtar kelime ara veya YouTube linki yapıştır...',
    searchButton: 'Ara',
    pasteLink: 'Link Yapıştır',
    singleDownload: 'İndir',
    addToBatch: 'Seç',
    selected: 'Seçildi',
    itemsSelected: 'Video Seçildi',
    itemSelected: 'Video Seçildi',
    clearAll: 'Temizle',
    downloadZip: 'ZIP İndir',
    formatLabel: 'Format',
    formatShort: 'F',
    qualityLabel: 'Kalite',
    qualityShort: 'K',
    viewList: 'Listeyi Gör',
    readyToProcess: 'İşleme hazır',
    downloading: 'İndiriliyor...',
    processing: 'ZIP Oluşturuluyor...',
    completed: 'İndirme Hazır',
    failed: 'İşlem Başarısız',
    saveFile: 'Cihaza Kaydet',
    preparing: 'Hazırlanıyor...',
    waiting: 'Bekleniyor',
    success: 'Başarılı',
    error: 'Hata',
    terms: 'Kullanım Şartları',
    privacy: 'Gizlilik Politikası',
    cookies: 'Çerez Politikası',
    legal: 'Yasal Uyarı',
    howItWorks: 'Nasıl çalışır',
    faq: 'SSS',
    supportedSites: 'Desteklenen siteler',
    close: 'Kapat',
    acceptCookies: 'Kabul Et',
    cookieMessage: 'En iyi deneyimi sağlamak için çerezleri kullanıyoruz.',
    metadataUnavailable: 'Meta veriler mevcut değil',
    noItemsSelected: 'Seçili öğe yok',
    unknownChannel: 'Kanal bilgisi yok',
    remove: 'Kaldır',
    backToSearch: 'Aramaya Dön',
    allRightsReserved: 'Tüm hakları saklıdır.',
    batchCompleted: 'Toplu İndirme Tamamlandı',
    batchFailed: 'Toplu İndirme Başarısız',
    waitingInQueue: 'Kuyrukta bekleniyor...',
    preparingDownload: 'İndirme hazırlanıyor...',
    noResultsAvailable: 'Sonuç yok',
    succeededLabel: 'tamamlandı',
    itemsLabel: 'öğe',
    itemLabel: 'Öğe',
    cookie: {
      message: 'BatchTube çerezleri yalnızca site işlevselliği ve reklam gösterimi için kullanır.',
      accept: 'Kabul Et',
      reject: 'Reddet',
      essential: 'Sadece Gerekli',
      reset: 'Çerez Tercihlerini Sıfırla'
    }
  },
  pt: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'Download em Lote. Simplificado.',
    heroSubtitle: 'Motor paralelo de alta velocidade. Sem anúncios.',
    searchPlaceholder: 'Pesquisar ou colar link do YouTube...',
    searchButton: 'Buscar',
    pasteLink: 'Colar Link',
    singleDownload: 'Baixar',
    addToBatch: 'Selecionar',
    selected: 'Selecionado',
    itemsSelected: 'Vídeos Selecionados',
    itemSelected: 'Vídeo Selecionado',
    clearAll: 'Limpar',
    downloadZip: 'Baixar ZIP',
    formatLabel: 'Formato',
    formatShort: 'F',
    qualityLabel: 'Qualidade',
    qualityShort: 'Q',
    viewList: 'Ver Lista',
    readyToProcess: 'Pronto para Processar',
    downloading: 'Baixando...',
    processing: 'Criando ZIP...',
    completed: 'Pronto para Baixar',
    failed: 'Falha na Operação',
    saveFile: 'Salvar Arquivo',
    preparing: 'Preparando...',
    waiting: 'Aguardando',
    success: 'Sucesso',
    error: 'Erro',
    terms: 'Termos de Uso',
    privacy: 'Privacidade',
    cookies: 'Cookies',
    legal: 'Aviso Legal',
    howItWorks: 'Como funciona',
    faq: 'Perguntas frequentes',
    supportedSites: 'Sites suportados',
    close: 'Fechar',
    acceptCookies: 'Aceitar',
    cookieMessage: 'Usamos cookies para garantir a melhor experiência.',
    metadataUnavailable: 'Metadados indisponíveis',
    noItemsSelected: 'Nenhum item selecionado',
    unknownChannel: 'Canal indisponível',
    remove: 'Remover',
    backToSearch: 'Voltar à Busca',
    allRightsReserved: 'Todos os direitos reservados.',
    batchCompleted: 'Lote Concluído',
    batchFailed: 'Lote Falhou',
    waitingInQueue: 'Aguardando na fila...',
    preparingDownload: 'Preparando download...',
    noResultsAvailable: 'Nenhum resultado disponível',
    succeededLabel: 'concluídos',
    itemsLabel: 'itens',
    itemLabel: 'Item',
    cookie: {
      message: 'BatchTube usa cookies apenas para funcionalidade do site e exibição de anúncios.',
      accept: 'Aceitar',
      reject: 'Rejeitar',
      essential: 'Apenas Essenciais',
      reset: 'Redefinir Preferências de Cookies'
    }
  },
  ar: {
    ...BASE_TRANSLATIONS,
    heroTitle: 'تحميل جماعي. مبسط.',
    heroSubtitle: 'محرك متوازي عالي السرعة. بدون إعلانات.',
    searchPlaceholder: 'ابحث أو الصق رابط يوتيوب...',
    searchButton: 'بحث',
    pasteLink: 'لصق الرابط',
    singleDownload: 'تحميل',
    addToBatch: 'تحديد',
    selected: 'محدد',
    itemsSelected: 'فيديو محدد',
    itemSelected: 'فيديو محدد',
    clearAll: 'مسح',
    downloadZip: 'تحميل ZIP',
    formatLabel: 'التنسيق',
    formatShort: 'ت',
    qualityLabel: 'الجودة',
    qualityShort: 'ج',
    viewList: 'عرض القائمة',
    readyToProcess: 'جاهز للمعالجة',
    downloading: 'جاري التحميل...',
    processing: 'جارٍ إنشاء ZIP...',
    completed: 'جاهز للتحميل',
    failed: 'فشل العملية',
    saveFile: 'حفظ الملف',
    preparing: 'جارٍ التحضير...',
    waiting: 'انتظار',
    success: 'نجاح',
    error: 'خطأ',
    terms: 'شروط الاستخدام',
    privacy: 'سياسة الخصوصية',
    cookies: 'سياسة ملفات تعريف الارتباط',
    legal: 'إشعار قانوني',
    howItWorks: 'كيف يعمل',
    faq: 'الأسئلة الشائعة',
    supportedSites: 'المواقع المدعومة',
    close: 'إغلاق',
    acceptCookies: 'قبول',
    cookieMessage: 'نستخدم ملفات تعريف الارتباط لضمان أفضل تجربة.',
    metadataUnavailable: 'البيانات غير متوفرة',
    noItemsSelected: 'لا توجد عناصر محددة',
    unknownChannel: 'القناة غير متوفرة',
    remove: 'إزالة',
    backToSearch: 'العودة للبحث',
    allRightsReserved: 'جميع الحقوق محفوظة.',
    batchCompleted: 'اكتمل التنزيل الجماعي',
    batchFailed: 'فشل التنزيل الجماعي',
    waitingInQueue: 'الانتظار في الطابور...',
    preparingDownload: 'جارٍ تجهيز التنزيل...',
    noResultsAvailable: 'لا توجد نتائج',
    succeededLabel: 'تم',
    itemsLabel: 'عناصر',
    itemLabel: 'عنصر',
    cookie: {
      message: 'BatchTube يستخدم ملفات تعريف الارتباط فقط لوظائف الموقع وعرض الإعلانات.',
      accept: 'قبول',
      reject: 'رفض',
      essential: 'الأساسية فقط',
      reset: 'إعادة تعيين تفضيلات ملفات تعريف الارتباط'
    }
  }
};

export const LEGAL_TEXTS: Record<SupportedLanguage, Record<LegalDocType, string>> = {
  en: {
    terms: `BatchTube Terms of Service\n\n1. Acceptance\nBy using BatchTube, you agree to these terms.\n\n2. Usage\nThis tool is for personal, educational use only. You must comply with YouTube's Terms of Service.\n\n3. Liability\nBatchTube is not responsible for copyright infringement caused by users.`,
    privacy: `Privacy Policy\n\n1. Data Collection\nWe do not store user data permanently. Download logs are cleared regularly.\n\n2. Third Parties\nWe use Google AdSense which may collect anonymous usage data.`,
    cookies: `Cookie Policy\n\nWe use essential cookies to manage your session and preferences. AdSense uses cookies to serve relevant ads.`,
    legal: `Legal Notice\n\nBatchTube is not affiliated with Google LLC or YouTube. All trademarks belong to their respective owners.`
  },
  es: {
    terms: `Términos de Servicio de BatchTube\n\n1. Aceptación\nAl usar BatchTube, aceptas estos términos.\n\n2. Uso\nEsta herramienta es solo para uso personal y educativo. Debes cumplir con los Términos de Servicio de YouTube.\n\n3. Responsabilidad\nBatchTube no es responsable de infracciones de copyright causadas por los usuarios.`,
    privacy: `Política de Privacidad\n\n1. Recolección de datos\nNo almacenamos datos de usuario de forma permanente. Los registros de descarga se eliminan regularmente.\n\n2. Terceros\nUsamos Google AdSense, que puede recopilar datos de uso anónimos.`,
    cookies: `Política de Cookies\n\nUsamos cookies esenciales para gestionar tu sesión y preferencias. AdSense usa cookies para anuncios relevantes.`,
    legal: `Aviso Legal\n\nBatchTube no está afiliado con Google LLC ni YouTube. Todas las marcas pertenecen a sus propietarios.`
  },
  fr: {
    terms: `Conditions d'utilisation de BatchTube\n\n1. Acceptation\nEn utilisant BatchTube, vous acceptez ces conditions.\n\n2. Utilisation\nCet outil est réservé à un usage personnel et éducatif. Vous devez respecter les Conditions d'utilisation de YouTube.\n\n3. Responsabilité\nBatchTube n'est pas responsable des violations de copyright causées par les utilisateurs.`,
    privacy: `Politique de confidentialité\n\n1. Collecte des données\nNous ne stockons pas les données utilisateur de façon permanente. Les journaux de téléchargement sont supprimés régulièrement.\n\n2. Tiers\nNous utilisons Google AdSense, qui peut collecter des données d'utilisation anonymes.`,
    cookies: `Politique de cookies\n\nNous utilisons des cookies essentiels pour gérer votre session et vos préférences. AdSense utilise des cookies pour des annonces pertinentes.`,
    legal: `Mentions légales\n\nBatchTube n'est pas affilié à Google LLC ou YouTube. Toutes les marques appartiennent à leurs propriétaires.`
  },
  de: {
    terms: `BatchTube Nutzungsbedingungen\n\n1. Akzeptanz\nDurch die Nutzung von BatchTube akzeptierst du diese Bedingungen.\n\n2. Nutzung\nDieses Tool ist nur für den persönlichen und bildungsbezogenen Gebrauch bestimmt. Du musst die YouTube-Nutzungsbedingungen einhalten.\n\n3. Haftung\nBatchTube ist nicht verantwortlich für Urheberrechtsverletzungen durch Nutzer.`,
    privacy: `Datenschutz\n\n1. Datenerhebung\nWir speichern keine Nutzerdaten dauerhaft. Download-Protokolle werden regelmäßig gelöscht.\n\n2. Drittanbieter\nWir verwenden Google AdSense, das anonyme Nutzungsdaten erfassen kann.`,
    cookies: `Cookie-Richtlinie\n\nWir verwenden essentielle Cookies zur Verwaltung deiner Sitzung und Präferenzen. AdSense verwendet Cookies für relevante Anzeigen.`,
    legal: `Rechtliche Hinweise\n\nBatchTube ist nicht mit Google LLC oder YouTube verbunden. Alle Marken gehören ihren jeweiligen Eigentümern.`
  },
  tr: {
    terms: `BatchTube Kullanım Şartları\n\n1. Kabul\nBatchTube'u kullanarak bu şartları kabul etmiş olursunuz.\n\n2. Kullanım\nBu araç yalnızca kişisel ve eğitim amaçlıdır. YouTube Kullanım Şartlarına uymalısınız.\n\n3. Sorumluluk\nBatchTube, kullanıcıların yaptığı telif ihlallerinden sorumlu değildir.`,
    privacy: `Gizlilik Politikası\n\n1. Veri Toplama\nKullanıcı verilerini kalıcı olarak saklamıyoruz. İndirme kayıtları düzenli olarak temizlenir.\n\n2. Üçüncü Taraflar\nGoogle AdSense kullanıyoruz; anonim kullanım verileri toplayabilir.`,
    cookies: `Çerez Politikası\n\nOturum ve tercihleri yönetmek için gerekli çerezler kullanılır. AdSense, ilgili reklamlar için çerez kullanır.`,
    legal: `Yasal Uyarı\n\nBatchTube, Google LLC veya YouTube ile bağlantılı değildir. Tüm markalar sahiplerine aittir.`
  },
  pt: {
    terms: `Termos de Serviço do BatchTube\n\n1. Aceitação\nAo usar o BatchTube, você concorda com estes termos.\n\n2. Uso\nEsta ferramenta é apenas para uso pessoal e educacional. Você deve cumprir os Termos de Serviço do YouTube.\n\n3. Responsabilidade\nO BatchTube não é responsável por violações de direitos autorais causadas pelos usuários.`,
    privacy: `Política de Privacidade\n\n1. Coleta de dados\nNão armazenamos dados do usuário permanentemente. Os registros de download são limpos regularmente.\n\n2. Terceiros\nUsamos o Google AdSense, que pode coletar dados de uso anônimos.`,
    cookies: `Política de Cookies\n\nUsamos cookies essenciais para gerenciar sua sessão e preferências. O AdSense usa cookies para anúncios relevantes.`,
    legal: `Aviso Legal\n\nO BatchTube não é afiliado ao Google LLC ou ao YouTube. Todas as marcas pertencem aos seus proprietários.`
  },
  ar: {
    terms: `شروط استخدام BatchTube\n\n1. القبول\nباستخدام BatchTube فإنك توافق على هذه الشروط.\n\n2. الاستخدام\nهذه الأداة للاستخدام الشخصي والتعليمي فقط. يجب الالتزام بشروط خدمة YouTube.\n\n3. المسؤولية\nBatchTube غير مسؤول عن انتهاكات حقوق النشر التي يقوم بها المستخدمون.`,
    privacy: `سياسة الخصوصية\n\n1. جمع البيانات\nلا نقوم بتخزين بيانات المستخدم بشكل دائم. يتم حذف سجلات التنزيل بشكل دوري.\n\n2. أطراف ثالثة\nنستخدم Google AdSense الذي قد يجمع بيانات استخدام مجهولة.`,
    cookies: `سياسة ملفات تعريف الارتباط\n\nنستخدم ملفات تعريف الارتباط الأساسية لإدارة الجلسة والتفضيلات. يستخدم AdSense ملفات تعريف الارتباط للإعلانات المناسبة.`,
    legal: `إشعار قانوني\n\nBatchTube غير تابع لـ Google LLC أو YouTube. جميع العلامات التجارية تعود لأصحابها.`
  }
};

export const INFO_TEXTS: Record<SupportedLanguage, Record<InfoPageType, string>> = {
  en: {
    howItWorks: `How It Works\n\n1. Paste a YouTube URL or search by keyword.\n2. Select videos and choose format/quality.\n3. Start the batch and download the ZIP when ready.`,
    faq: `FAQ\n\nQ: Is this free?\nA: Yes, it's free to use.\n\nQ: Do you store my files?\nA: No, downloads are processed temporarily.\n\nQ: Why can't I download some videos?\nA: Some videos may be restricted or unavailable.`,
    supportedSites: `Supported Sites\n\n- YouTube (videos and shorts)\n- youtu.be short links\nMore platforms may be added over time.`
  },
  es: {
    howItWorks: `Cómo funciona\n\n1. Pega un URL de YouTube o busca por palabra clave.\n2. Selecciona videos y elige formato/calidad.\n3. Inicia el lote y descarga el ZIP cuando esté listo.`,
    faq: `Preguntas frecuentes\n\nP: ¿Es gratis?\nR: Sí, es gratuito.\n\nP: ¿Guardan mis archivos?\nR: No, las descargas se procesan temporalmente.\n\nP: ¿Por qué no puedo descargar algunos videos?\nR: Algunos videos pueden estar restringidos o no disponibles.`,
    supportedSites: `Sitios compatibles\n\n- YouTube (videos y shorts)\n- Enlaces cortos youtu.be\nSe añadirán más plataformas con el tiempo.`
  },
  fr: {
    howItWorks: `Comment ça marche\n\n1. Collez un lien YouTube ou recherchez par mot-clé.\n2. Sélectionnez des vidéos et choisissez le format/la qualité.\n3. Lancez le lot et téléchargez le ZIP une fois prêt.`,
    faq: `FAQ\n\nQ : Est-ce gratuit ?\nR : Oui, c'est gratuit.\n\nQ : Stockez-vous mes fichiers ?\nR : Non, les téléchargements sont temporaires.\n\nQ : Pourquoi ne puis-je pas télécharger certaines vidéos ?\nR : Certaines vidéos peuvent être restreintes ou indisponibles.`,
    supportedSites: `Sites pris en charge\n\n- YouTube (vidéos et shorts)\n- Liens courts youtu.be\nD'autres plateformes pourront être ajoutées.`
  },
  de: {
    howItWorks: `So funktioniert es\n\n1. Füge eine YouTube-URL ein oder suche per Keyword.\n2. Wähle Videos und Format/Qualität.\n3. Starte den Batch und lade das ZIP herunter, wenn es bereit ist.`,
    faq: `FAQ\n\nF: Ist das kostenlos?\nA: Ja, es ist kostenlos.\n\nF: Speichert ihr meine Dateien?\nA: Nein, Downloads werden nur temporär verarbeitet.\n\nF: Warum kann ich einige Videos nicht herunterladen?\nA: Einige Videos können eingeschränkt oder nicht verfügbar sein.`,
    supportedSites: `Unterstützte Seiten\n\n- YouTube (Videos und Shorts)\n- youtu.be Kurzlinks\nWeitere Plattformen können später hinzugefügt werden.`
  },
  tr: {
    howItWorks: `Nasıl çalışır\n\n1. YouTube URL'si yapıştırın veya anahtar kelimeyle arayın.\n2. Videoları seçin ve format/kaliteyi belirleyin.\n3. Toplu işlemi başlatın ve hazır olduğunda ZIP'i indirin.`,
    faq: `SSS\n\nS: Ücretsiz mi?\nC: Evet, ücretsizdir.\n\nS: Dosyalarımı saklıyor musunuz?\nC: Hayır, indirmeler geçici olarak işlenir.\n\nS: Bazı videoları neden indiremem?\nC: Bazı videolar kısıtlı veya kullanılamaz olabilir.`,
    supportedSites: `Desteklenen siteler\n\n- YouTube (videolar ve shorts)\n- youtu.be kısa bağlantıları\nZamanla daha fazla platform eklenebilir.`
  },
  pt: {
    howItWorks: `Como funciona\n\n1. Cole um URL do YouTube ou pesquise por palavra-chave.\n2. Selecione vídeos e escolha formato/qualidade.\n3. Inicie o lote e baixe o ZIP quando estiver pronto.`,
    faq: `Perguntas frequentes\n\nP: É grátis?\nR: Sim, é gratuito.\n\nP: Vocês armazenam meus arquivos?\nR: Não, os downloads são processados temporariamente.\n\nP: Por que não consigo baixar alguns vídeos?\nR: Alguns vídeos podem estar restritos ou indisponíveis.`,
    supportedSites: `Sites suportados\n\n- YouTube (vídeos e shorts)\n- Links curtos youtu.be\nMais plataformas podem ser adicionadas no futuro.`
  },
  ar: {
    howItWorks: `كيف يعمل\n\n1. الصق رابط يوتيوب أو ابحث بكلمة مفتاحية.\n2. اختر المقاطع وحدد التنسيق/الجودة.\n3. ابدأ الدفعة وحمّل ملف ZIP عند الجاهزية.`,
    faq: `الأسئلة الشائعة\n\nس: هل الخدمة مجانية؟\nج: نعم، مجانية.\n\nس: هل تخزنون ملفاتي؟\nج: لا، تتم معالجة التنزيلات مؤقتًا.\n\nس: لماذا لا يمكنني تنزيل بعض المقاطع؟\nج: قد تكون بعض المقاطع مقيدة أو غير متاحة.`,
    supportedSites: `المواقع المدعومة\n\n- YouTube (فيديوهات و Shorts)\n- روابط youtu.be القصيرة\nقد تتم إضافة منصات أخرى لاحقًا.`
  }
};
